language: java
sudo: false
before_script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test -B
- mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - .autoconf
  - $HOME/.m2